### ISSUE TITLE
Error en periodo de liquidación en odoo 8

### ISSUE THREAD

**Issue by deifler90** [Pexego/sale_commission#1]
Buenos días,

Cuando intento liquidar las comisiones no puedo, ya que me dice que el periodo de liquidación no es válido, el caso es que no puedo modificarlo.

Adjunto imagen a ver si es os ocurre algo.

Gracias!
![captura](https://cloud.githubusercontent.com/assets/6301623/5815323/123d6d72-a095-11e4-8b92-6055fee832ed.PNG)

**Comment by jesusVMayor** [comment]
En la vista lista de agentes hay un asistente para crear las liquidaciones.

**Comment by deifler90** [comment]
Gracias por responder, creo que no aparece, te refieres aquí?
![captura](https://cloud.githubusercontent.com/assets/6301623/5836934/1086125e-a17b-11e4-98e0-2e4855d80cf5.PNG)

**Comment by deifler90** [comment]
Cierto, lo he encontrado, está dentro de más, voy a probarlo, gracias!
